[Refactor:Plagiarism] Rebranding Lichen
Submitty/Lichen pull request #64
Opened 2021-09-22 21:00 UTC by sbelsk

### What is the current behavior?
All places in the code base refer to the number of tokens that make up a hash as `sequence length` and many places refer to other gradeables as `prior term gradeables`

### What is the new behavior?
The term `sequence length` is now referred to as `hash size`, and `prior term gradeables` are referred to as `other gradeables`. All previous references to the old names have been changed for consistency. Related PR's will be made in all other repositories to update these terms.

### Other information?
No changes in the behavior of any program/script, except for two parameters in the `config.json` that were renamed:
- "sequence_length" is now "hash_size"
- "prior_term_gradeables" is now "other_gradeables", and its sub-keys are also changed:
    - "prior_semester"     -> "other_semester"
    - "prior_course"       -> "other_course"
    - "prior_gradeable"    -> "other_gradeable"

Due to this change, this PR has to be merged and released together with the PR on the main Submitty repo.

2021-09-23 20:13 UTC, williamjallen requested changes
Changes mostly look good but I did suggest two changes.  In addition, this PR depends on an upcoming PR on the Submitty side, as well as https://github.com/Submitty/Lichen/pull/63 which will cause a few minor merge conflicts.

2021-09-23 20:13 UTC, williamjallen commented on bin/concatenate_all.py
> +    for ptg in other_gradeables:
perhaps `ptg` isn't the best name here anymore?

2021-09-23 20:13 UTC, williamjallen commented on bin/concatenate_all.py
> +    for ptg in other_gradeables:
same here about `ptg`

2021-10-11 19:07 UTC, williamjallen approved these changes

2021-10-11 22:06 UTC, MasterOdin commented
@sbelsk looks like there's a PR conflict, would you be able to resolve it?

2021-10-25 20:11 UTC, merged